plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.6.1'
    id 'io.papermc.paperweight.userdev' version '2.0.0-beta.24'
}

group = 'com.markaptogo'
def baseVer = project.findProperty('baseVersion') ?: '1.0'
def offset = (project.findProperty('buildOffset') ?: '10').toInteger()
def runNum = (project.findProperty('buildNumber') ?: '1').toInteger()
def defaultVer = "${baseVer}.${offset + runNum}"
version = project.findProperty('pluginVersion') ?: defaultVer

repositories {
    mavenCentral()
    maven {
        name = 'papermc-repo'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }

    // Okaeri Config
    maven { url = 'https://storehouse.okaeri.eu/repository/maven-public/' }
}

dependencies {
    paperweight.paperDevBundle('26.2.build.129-stable')

    implementation 'eu.okaeri:okaeri-configs-yaml-bukkit:5.0.8'
    implementation 'eu.okaeri:okaeri-configs-serdes-bukkit:5.0.8'
    implementation 'eu.okaeri:okaeri-configs-serdes-commons:5.0.8'
    implementation 'eu.okaeri:okaeri-configs-validator-okaeri:5.0.8'

    testImplementation platform('org.junit:junit-bom:6.1.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

def targetJavaVersion = 25
java {
    toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(targetJavaVersion)
    options.compilerArgs += ['-parameters']
}

tasks.jar {
    archiveClassifier.set('dev')
}

tasks.shadowJar {
    archiveClassifier.set('')

    relocate('eu.okaeri', 'com.markaptogo.optimizationutils.libs.eu.okaeri')
}

tasks.test {
    useJUnitPlatform()
}

tasks.assemble {
    dependsOn(tasks.shadowJar)
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset = 'UTF-8'
    filesMatching('paper-plugin.yml') {
        expand props
    }
}
