name: OptimizationUtils
version: '${version}'
main: com.markaptogo.optimizationutils.OptimizationUtils
api-version: '26.2'
authors: [EpicPlayerA10, MARKAPTOGO]
website: https://stylelabor.de
description: A minecraft plugin with some useful optimization utils.
permissions:
  optimizationutils.admin:
    description: Allows using the /optimizationutils command
    default: op
